name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    
    - name: Setup database
      run: |
        bundle exec rails db:create db:schema:load RAILS_ENV=test || true
    
    - name: Run linters and security checks
      run: |
        bundle exec rubocop --parallel || true
        bundle exec brakeman -q -w2 || true
